feat: publish docker node
paritytech/extended-parachain-template pull request #93
Opened 2023-10-25 13:48 UTC by Moliholy

Closes #74

2023-10-25 15:48 UTC, stiiifff requested changes

2023-10-25 15:48 UTC, stiiifff commented on .github/workflows/publish-docker.yml
docker login, metadata & build-push actions could be bumped to v3.0.0, v5.0.0 and v5.0.0 respectively (see Trappist's [publish-docker workflow](https://github.com/paritytech/trappist/blob/main/.github/workflows/publish-docker.yml)).

2023-10-26 10:33 UTC, Moliholy commented on .github/workflows/publish-docker.yml
Fixed in [30d192b](https://github.com/paritytech/extended-parachain-template/pull/93/commits/30d192bfa70907f17f95ac0a29aaefd1737d5ac3).

2023-11-02 10:24 UTC, stiiifff approved these changes

2023-11-02 10:27 UTC, stiiifff commented
Thanks @Moliholy, LGTM !

2023-11-02 10:27 UTC, merged