Fix polkadot build
paritytech/extended-parachain-template pull request #95
Opened 2023-10-26 13:40 UTC by khssnv

* Repository renamed, should `pushd` a renamed dir too,
* Branch naming pattern now has a `polkadot-` prefix, example: https://github.com/paritytech/polkadot-sdk/tree/polkadot-v1.1.0
* Build creates 3 executables, all required to launch the relay chain

2023-11-02 16:50 UTC, Moliholy requested changes

2023-11-02 20:16 UTC, weezy20 reviewed
Is the added complexity of a bash array needed? Isn't it simpler to just copy `polkadot` and the workers with 3 `cp` commands?

2023-11-06 14:48 UTC, khssnv commented on zombienet.sh
> +      cp ${POLKADOT_FILES[@]/#/target/release/} $CWD/bin
Quotes added.

2023-11-06 14:48 UTC, khssnv commented
> Is the added complexity of a bash array needed? Isn't it simpler to just copy `polkadot` and the workers with 3 `cp` commands?

Array expansion removed.

2023-11-06 14:50 UTC, Moliholy approved these changes

2023-11-07 14:44 UTC, weezy20 approved these changes
Lgtm! Thanks @khssnv

2023-11-08 09:05 UTC, merged